### PR TITLE
Linux support prep

### PR DESCRIPTION
**Pull request by erinzm**
Adding *nix support.
TODO:
- [x] Split and organize such that Win stuff is seperate from *Nix stuff
- [ ] Port some utils from Batch to bash files
- [ ] Figure out best Linux way of finding out if apps are installed
- [ ] Port config/install system to Bash
- [ ] Port network stuff to ip/ifconfig/iptables

### CODE REVIEW

**Comment by dmssargent** [comment]
I'm about to add the old *nix to the repo, I think License may need to changed to GPL (to bundle Windws utilities), but I'm not sure yet. I will work on integrating your changes to the existing

**Comment by dmssargent** [comment]
The basic Linux support is done, any new changes reguarding *nix will be commited a new linux-dev branch. For Windows, this will be new win-dev branch.

**Comment by dmssargent** [comment]
And how did I not see that Do Not Merge request. Ugh, sorry about that. I really need to use GitHub more often. There is a linux-dev branch, so I think I can merge this there, without affecting master.

**Comment by erinzm** [comment]
Actually, all this PR at the point you merged it did, is move the files around to prepare for linux support. It didn't actually add linux support, so I'll have to reopen another pull-request targetted at linux-dev.

**Comment by dmssargent** [comment]
Sorry, about that I did add a small amount of edits and merge with my nix-branch which then got merged with the main branch which should have been the linux-dev, but I didn't know that at the time, I added a tiny stub to "configure.unix.sh", and took care of "wlan-conf-parser.bat" that got left open with that change. And what I mean by very basic support, is that a "autogen.sh" was added (and the corresponding Autotools files)

**Comment by dmssargent** [comment]
You are more than welcome to open another pull request, it just that I need to use GitHub more often to understand what exactly each button does and how it affects the project.

**Pull request merged**
